In [58]:
import numpy as np

In [8]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [9]:
np.array(my_list)

array([1, 2, 3])

In [10]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
my_list3 = [
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]]
]

In [13]:
np.array(my_list3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [14]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [76]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [77]:
np.zeros((8,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
np.ones(3)

array([1., 1., 1.])

In [20]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [23]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [75]:
np.random.rand(3)

array([0.65649702, 0.84745682, 0.53148898])

In [25]:
np.random.rand(5,5)

array([[0.81268865, 0.13125064, 0.27432829, 0.40775991, 0.07012584],
       [0.64661108, 0.88578992, 0.31427872, 0.3998    , 0.70043735],
       [0.44520782, 0.05024763, 0.00637289, 0.28613789, 0.4866981 ],
       [0.56348991, 0.2400531 , 0.56386758, 0.13001508, 0.65131236],
       [0.51968652, 0.1865923 , 0.33743847, 0.40184358, 0.42609538]])

In [73]:
np.random.randn(5)

array([-2.03688319, -0.04083147, -1.65975226,  1.370643  ,  1.6725077 ])

In [72]:
np.random.randn(6,6)

array([[ 0.72981308, -0.23545649, -0.21343299,  0.78013039, -0.49325561,
         0.92931565],
       [ 1.04765422, -1.00632796, -0.58790234,  1.94639548, -0.57339302,
         2.63150348],
       [ 1.21290731, -0.47170357, -0.59983245,  1.88179022,  1.01582644,
        -0.8503462 ],
       [ 0.08243058, -1.29847393,  1.8934532 , -0.2582234 , -1.65954295,
        -1.09833367],
       [ 2.19104141,  0.37413992, -1.04269451,  0.43017834,  1.14100825,
         0.37146024],
       [-0.67283762,  0.17358726,  0.01713069, -1.74487999, -1.7846057 ,
         1.18215924]])

In [28]:
np.random.randint(1,100)

4

In [71]:
np.random.randint(1,100,20)

array([22, 84, 33,  8, 29, 23, 42, 92, 38, 32, 68, 44, 20, 76, 78, 89, 11,
       62,  7,  5])

In [30]:
my_list = [1,2,3]
array_1d = np.array(my_list)

my_list2 = [[1,2,3],[4,5,6],[7,8,9]]
array_2d = np.array(my_list2)

my_list3 = [
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]]
]
array_3d = np.array(my_list3)

In [31]:
array_1d.shape

(3,)

In [32]:
array_2d.shape

(3, 3)

In [34]:
array_3d.shape

(3, 3, 3)

In [35]:
arr

NameError: name 'arr' is not defined

In [36]:
arr.shape

NameError: name 'arr' is not defined

In [38]:
arr.reshape(1,25)

NameError: name 'arr' is not defined

In [39]:
arr.reshape(1,25).shape

NameError: name 'arr' is not defined

In [40]:
arr.reshape(5,5)

NameError: name 'arr' is not defined

In [41]:
arr.reshape(25,1)

NameError: name 'arr' is not defined

In [42]:
arr.reshape(25,1).shape

NameError: name 'arr' is not defined

In [43]:
array_2d.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
array_2d.reshape(-1).shape

(9,)

In [45]:
array_3d.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [46]:
array_3d.reshape(-1).shape

(27,)

In [47]:
ranarr

NameError: name 'ranarr' is not defined

In [48]:
ranarr.max()

NameError: name 'ranarr' is not defined

In [49]:
ranarr.argmax()

NameError: name 'ranarr' is not defined

In [50]:
ranarr.min()

NameError: name 'ranarr' is not defined

In [51]:
ranarr.argmin()

NameError: name 'ranarr' is not defined

In [52]:
arr.dtype


NameError: name 'arr' is not defined

In [70]:
arr1 = np.linspace(0,30,5)
arr1.dtype

#berhenti disini

dtype('float64')

In [68]:
arr = np.arange(0,30)

In [69]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [78]:
arr[10]

10

In [79]:
arr[2:15]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [80]:
arr[0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
arr[1:15:3]

array([ 1,  4,  7, 10, 13])

In [83]:
arr[0:10]=20
#show arr
arr

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [84]:
arr = np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
slice_of_arr = arr[0:6]

#show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [86]:
slice_of_arr[:] = 50

slice_of_arr

array([50, 50, 50, 50, 50, 50])

In [87]:
arr

array([50, 50, 50, 50, 50, 50,  6,  7,  8,  9, 10])

In [88]:
arr_copy = arr.copy()

arr_copy

array([50, 50, 50, 50, 50, 50,  6,  7,  8,  9, 10])

In [91]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [90]:
arr_2d[1]

array([20, 25, 30])

In [92]:
arr_2d[2][2]

45

In [93]:
arr_2d[1,1]

25

In [94]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [95]:
arr_2d[:,0]

array([ 5, 20, 35])

In [98]:
arr = np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
[arr[2], arr[8], arr[9]]

[2, 8, 9]

In [103]:
arr[[0,7,6]]

array([0, 7, 6])

In [105]:
arr[[3,4,8]]

array([3, 4, 8])

In [106]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [107]:
arr_2d[[1,0]]

array([[20, 25, 30],
       [ 5, 10, 15]])

In [108]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [109]:
arr % 2 != 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [110]:
bool_arr = arr % 2 != 0

In [111]:
bool_arr

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [112]:
arr[bool_arr]

array([1, 3, 5, 7, 9])

In [113]:
arr[arr % 2 != 0]

array([1, 3, 5, 7, 9])

In [114]:
hasil = 5
arr[arr <= hasil]

array([1, 2, 3, 4, 5])